sudo: false
language: python
python: 3.5
cache: pip
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
install:
  - travis_retry pip install tox
  - travis_retry pip install coveralls
script:
  - travis_retry tox
after_success:
  - coverage run --source=pandas_validator setup.py test
  - coveralls

