sudo: false
language: python
python: 3.6
cache:
  directories:
    - "$HOME/.tox"
before_cache:
  - rm -f $HOME/.tox/$TOXENV/log/*.log
env:
  - TOXENV=py27-pandas18
  - TOXENV=py27-pandas19
  - TOXENV=py34-pandas18
  - TOXENV=py34-pandas19
  - TOXENV=py36-pandas18
  - TOXENV=py36-pandas19
  - TOXENV=flake8
install:
  - travis_retry pip install -q tox coveralls
  - travis_retry pip install -q -r requirements/general.txt
script:
  - travis_retry tox
after_success:
  - coverage run --source=pandas_validator setup.py test
  - coveralls
notifications:
  email: false
