sudo: false
language: python
python: 2.7
env:
  - TOXENV=py27
  - TOXENV=py34
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
  - coverage run --source=pandas_validator setup.py test
after_success:
  - coveralls
