sudo: false
language: python
python: 3.5
cache:
  directories:
    - $HOME/.tox
before_cache:
  - rm -f $HOME/.tox/$TOXENV/log/*.log
env:
  - TOXENV=py27-pandas14
  - TOXENV=py27-pandas15
  - TOXENV=py27-pandas16
  - TOXENV=py27-pandas17

  - TOXENV=py33-pandas14
  - TOXENV=py33-pandas15
  - TOXENV=py33-pandas16
  - TOXENV=py33-pandas17

  - TOXENV=py34-pandas14
  - TOXENV=py34-pandas15
  - TOXENV=py34-pandas16
  - TOXENV=py34-pandas17

  - TOXENV=py35-pandas14
  - TOXENV=py35-pandas15
  - TOXENV=py35-pandas16
  - TOXENV=py35-pandas17

  - TOXENV=flake8

install:
  - travis_retry pip install -q tox
  - travis_retry pip install -q coveralls
script:
  - travis_retry tox
after_success:
  - coverage run --source=pandas_validator setup.py test
  - coveralls

