sudo: false
language: python
python: 2.7
cache: pip
env:
  - TOXENV=py27
  - TOXENV=py34
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coverage run --source=pandas_validator setup.py test
  - coveralls

